# Generated by Django 4.0.5 on 2022-07-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('date_from', models.DateField()),
                ('date_till', models.DateField()),
                ('pricing', models.FloatField()),
                ('guests_number', models.IntegerField()),
                ('images', models.ImageField(upload_to='assets/')),
            ],
            options={
                'db_table': 'Housings',
            },
        ),
    ]
